# Generated by Django 2.2.4 on 2019-08-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20190818_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, to='warehouse.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(blank=True, to='warehouse.Order'),
        ),
        migrations.AddField(
            model_name='product',
            name='segments',
            field=models.ManyToManyField(blank=True, to='warehouse.Segment'),
        ),
        migrations.AddField(
            model_name='segment',
            name='products',
            field=models.ManyToManyField(blank=True, to='warehouse.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
