# Generated by Django 2.2.4 on 2019-08-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20190818_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='product',
            name='segments',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='products',
        ),
    ]
