# Generated by Django 2.2.4 on 2019-08-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_auto_20190819_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='warehouse.Product'),
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
