# Generated by Django 2.2.4 on 2019-08-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_auto_20190818_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='segments',
            field=models.ManyToManyField(blank=True, to='warehouse.Segment'),
        ),
    ]
