# Generated by Django 2.2.4 on 2019-08-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_product_segments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='segments',
        ),
        migrations.AlterField(
            model_name='segment',
            name='products',
            field=models.ManyToManyField(through='warehouse.SegmentProduct', to='warehouse.Product'),
        ),
    ]
